name: Go
on:
  push:
    branches:
      - '**'
    # We already run this workflow on push to branch,
    # so we ignore push of tags
    tags-ignore:
      - "v*.*.*"
      - "v*.*.*-rc.*"
jobs:
  validator:
    name: Checks Validators
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@master
      - name: Set up Go 1.22
        uses: actions/setup-go@v5
        with:
          go-version: 1.22
      - name: Checks validator
        run: |
          make checks-validator

  test:
    name: Code Test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@master
      - name: Set up Go 1.22
        uses: actions/setup-go@v5
        with:
          go-version: 1.22
      - name: Run tests
        run: |
          make test
